<?
$hitItemsResult=$APPLICATION->IncludeComponent("bexx:catalog.items", "scroll_template_1", array(
	"IBLOCK_TYPE" => "catalog",
	"IBLOCK_ID" => "26",
	"ITEMS_SLIDER_COUNT" => "5",
	"CODE" => "hitItems",
	"ADDITIONAL_FILTER" => "",
	"SECTION_ID" => "0",
	"INCLUDE_SUBSECTIONS" => "Y",
	"ACTIVE" => "A",
	"ACTIVE_DATE" => "A",
	"GET_LINKED_ELEMENTS" => "Y",
	"GET_LINKED_SECTIONS" => "N",
	"FILTER_PROPS" => array(
	),
	"SKU_ALLOW" => "Y",
	"ALLOW_BUY_NOT_EXISTING" => "Y",
	"CHECK_PERMISSIONS" => "N",
	"CATALOG_PATH" => "/catalog/",
	"DESCRIPTION_FROM_PROPS" => "N",
	"COUNT" => "8",
	"ALLOW_PAGENAV" => "N",
	"SORT_FIELD_1" => "property_4392",
	"SORT_DIR_1" => "asc",
	"SORT_FIELD_2" => "shows",
	"SORT_DIR_2" => "desc,nulls",
	"SORTING_PANEL_OPTIONS" => array(
		0 => "price",
		1 => "name",
	),
	"SORTING_PANEL_OPTIONS_price" => "",
	"SORTING_PANEL_OPTIONS_name" => "",
	"CACHE_TYPE" => "A",
	"CACHE_TIME" => "3600",
	"CACHE_WITH_FILTER" => "N",
	"CACHE_WITH_SORTING" => "N",
	"CACHE_WITH_PAGING" => "N",
	"SET_TITLE" => "N",
	"CODE" => "hitItems",
	"SCROLL_SKIP" => "3",
	"BLOCK_TITLE" => "Популярные товары",
	"BLOCK_URL" => "/catalog/hit/",
	"BLOCK_URL_TITLE" => "",
	"BLOCK_IMAGE_SRC" => "/bitrix/templates/main/images/pic-hit.png"
	),
	$component
);
?>